In [32]:
import pandas as pd
import random
import numpy as np
import eh_translator as t

In [33]:
hungarian_multigraph_letters = ['cs', 'dz', 'dzs', 'gy', 'ly', 'ny', 'sz', 'ty', 'zs']

In [34]:
def get_corpus(df):
    #df = pd.read_csv('hu_50k.txt', on_bad_lines='skip', dtype=str, sep=' ').dropna()

    prefix_pattern = r'^(meg|át|fel|el|be|ki|elő|le|vissza|oda|ide|túl|körül|kör|felül|alul|kívül|belül|hátul|elől|hátra|előre|össze|szét|újra|felre|alá|oldal).+'
    df = df[
        df['szo'].notna() &
        (df['szo'].str.contains(prefix_pattern, regex=True, na=False) == False)
    ]


    # keep only A–Z + a–z + Hungarian letters
    #letters_only = r'^[A-Za-zÁÉÍÓÖŐÚÜŰáéíóöőúüű]+$'
    #df = df[df['szavak'].str.contains(letters_only, regex=True, na=False)]

    df['szo'] = df['szo'].str.lower()

    # Can only contains letters
    df = df[df['szo'].str.contains(r'^[a-záéíóöőúüű]+$', regex=True, na=False)]

    # Drop stopwords
    #df = df[~df['szavak'].isin(stopwords)]

    # Drop 1 letters
    df = df[~df['szo'].isin(hungarian_multigraph_letters)]

    df = df.drop_duplicates(subset=['szo'])
    #df = df[df['szavak'].str.len() > 3]

    CORPUS = df['szo'].values
    #random.shuffle(CORPUS)
    return CORPUS

In [35]:
df_corpus = pd.read_parquet('hu_50k_clead_with_pos.parquet')
print(len(df_corpus))   
corpus = get_corpus(df_corpus)

43276

/var/folders/59/v5dbhk2s3xx2rh5prvb8hs7r0000gn/T/ipykernel_41508/3187648891.py:7: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  (df['szo'].str.contains(prefix_pattern, regex=True, na=False) == False)
/var/folders/59/v5dbhk2s3xx2rh5prvb8hs7r0000gn/T/ipykernel_41508/3187648891.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['szo'] = df['szo'].str.lower()

In [36]:
print(len(corpus))

34763

In [37]:
def iter_splits_exact_parts(text: str, num_parts: int, min_part_len: int = 1):
    text_len = len(text)
    if num_parts <= 0 or text_len < num_parts * min_part_len:
        return 
    def search(start_index: int, parts_left: int, current_split: list[str]):
        if parts_left == 1:
            if text_len - start_index >= min_part_len:
                yield current_split + [text[start_index:]]
            return
        max_next_len = text_len - start_index - min_part_len * (parts_left - 1)
        for next_len in range(min_part_len, max_next_len + 1):
            yield from search(
                start_index + next_len,
                parts_left - 1,
                current_split + [text[start_index:start_index + next_len]],
            )
    yield from search(0, num_parts, [])

def all_splits_exact_parts(text: str, num_parts: int = 3, min_part_len: int = 1) -> list[list[str]]:
    return list(iter_splits_exact_parts(text, num_parts, min_part_len))

In [38]:
def create_all_combinations(df, num_parts = 3):
    df['chunks'] = df.corpus.apply(lambda x: all_splits_exact_parts(x, num_parts=num_parts))
    df_exp = df.explode('chunks').dropna(axis=0).reset_index(drop=True)

    cols = [f'chunk{x+1}' for x in range(num_parts)]
    df_exp[cols] = np.stack(df_exp['chunks'].to_numpy())

    return df_exp


def select_valid_elements(df, df_exp, num_parts, filter=True):
    msk = df_exp.chunk1.isin(df['corpus'])
    for i in range(2, num_parts+1):
        msk = msk & df_exp[f'chunk{i}'].isin(df['corpus'])

    if filter:
        for i in range(1, num_parts + 1):
            for j in range(i + 1, num_parts + 1):
                ab = df_exp[f'chunk{i}'] + df_exp[f'chunk{j}']
                ba = df_exp[f'chunk{j}'] + df_exp[f'chunk{i}']
                msk &= ~ab.isin(corpus) & ~ba.isin(corpus)
    
    df_valid = df_exp[msk].drop(columns=['chunks'])

    return df_valid

In [39]:
df = pd.DataFrame(corpus, columns=['corpus'])

In [40]:
non_last = ['adj', 'adv', 'con', 'sentint', 'adj_wh', 'adj_num_wh', 'prv', 'post', 'neg', 'abr']
df_exp = df_corpus.explode('po')
words_can_be_last = df_exp[df_exp['po'].isin(non_last)]['szo'].unique()
print(words_can_be_last)

['nem' 'hogy' 'és' ... 'esküvődre' 'gépi' 'terméketlen']

In [ ]:
for num_parts in range(2,5):
    df_exp = create_all_combinations(df, num_parts)
    df_valid = select_valid_elements(df, df_exp, num_parts, filter=False)
    # Remove where last part is 1 letter
    df_valid = df_valid[df_valid[f'chunk{num_parts}'].str.len() > 1]
    df_valid = df_valid[~df_valid[f'chunk{num_parts}'].isin(words_can_be_last)]
    
    remain_1 = np.sum([(df_valid[f'chunk{x}'].str.len() > 1) for x in range(1, num_parts)], axis=0)
    df_valid = df_valid[remain_1 > num_parts-2]

    remain_2 = np.sum([(df_valid[f'chunk{x}'].str.len() > 2) for x in range(1, num_parts+1)], axis=0)
    df_valid = df_valid[remain_2 > 0]



    df_valid.to_csv(f'word_combinations/{num_parts}_element_word_comibations.csv', index=False)

In [ ]:
df[df.corpus.isin([
    'de', 'hirda', 'tál', 'dehidratál'
])]

     corpus chunks
9        de     []
7901    tál     []

In [ ]:
df_valid[df_valid.corpus == 'terápiát']

Empty DataFrame
Columns: [corpus, chunk1, chunk2, chunk3, chunk4]
Index: []

In [ ]:
len(df_valid)

173