In [3]:
import pandas as pd
import seaborn as sns

In [22]:
import os, sys
import eh_translator as t

idx = t._load_or_build_indexes()
print('hun_to_eng size ->', len(idx['hun_to_eng']))
print('eng_to_hun size ->', len(idx['eng_to_hun']))

hun_to_eng size -> 139935
eng_to_hun size -> 90262

In [25]:
t.translate('kutya')

['dog']

In [46]:
df = pd.read_csv('words_with_distances_3.csv')
for word_column in ['chunk1', 'chunk2', 'chunk3', 'corpus']:
    logfreq_column = f'logfreq_{word_column}'
    updated_freq = []
    for i, item in df.iterrows():
        val = item[word_column]
        freq = item[logfreq_column] 
        if t.translate(val) is None:
            updated_freq.append(freq)
        else:
            updated_freq.append(max(freq, 4))
    df[logfreq_column] = updated_freq

In [47]:
df['logfreq_chunk1'].astype(int).value_counts()

logfreq_chunk1
4    6932
2    2146
3    1878
5     808
6     414
Name: count, dtype: int64

In [67]:
df_filtered = df[
    (df['logfreq_chunk1'] + df['length_chunk1'] > 6) &
    (df['logfreq_chunk2'] + df['length_chunk2'] > 6) &
    (df['logfreq_chunk3'] + df['length_chunk3'] > 6)
].copy()
print(len(df_filtered))
df_filtered.head(1)

1845

,count_of_chunks,corpus,chunk1,chunk2,chunk3,euclidean_distance_chunk1_and_chunk2,euclidean_distance_chunk1_and_chunk3,euclidean_distance_chunk2_and_chunk3,euclidean_corpus_and_chunk1,euclidean_corpus_and_chunk2,euclidean_corpus_and_chunk3,length_corpus,length_chunk1,length_chunk2,length_chunk3,logfreq_corpus,logfreq_chunk1,logfreq_chunk2,logfreq_chunk3
9,3,istenem,is,te,nem,10.594688,9.926656,9.824827,15.57864,15.443579,15.137335,7,2,2,3,5.070115,6.274002,5.976475,6.820146

In [68]:
df.columns

Index(['count_of_chunks', 'corpus', 'chunk1', 'chunk2', 'chunk3',
       'euclidean_distance_chunk1_and_chunk2',
       'euclidean_distance_chunk1_and_chunk3',
       'euclidean_distance_chunk2_and_chunk3', 'euclidean_corpus_and_chunk1',
       'euclidean_corpus_and_chunk2', 'euclidean_corpus_and_chunk3',
       'length_corpus', 'length_chunk1', 'length_chunk2', 'length_chunk3',
       'logfreq_corpus', 'logfreq_chunk1', 'logfreq_chunk2', 'logfreq_chunk3'],
      dtype='object')

In [69]:
 df_filtered['euclidean_corpus_and_chunk1']

9        15.578640
33       20.885342
63       22.975607
98       13.014709
114      24.859917
           ...
12162    21.038471
12163    21.038471
12169    27.818974
12173    14.328712
12174    13.865878
Name: euclidean_corpus_and_chunk1, Length: 1845, dtype: float64

In [75]:
df_filtered['sum_logfreq'] = df_filtered[['logfreq_chunk1', 'logfreq_chunk2', 'logfreq_chunk3']].sum(axis=1)
df_filtered['sum_distance'] = df_filtered[
       ['euclidean_corpus_and_chunk1', 'euclidean_corpus_and_chunk2', 'euclidean_corpus_and_chunk3']
].sum(axis=1) - df_filtered[['euclidean_distance_chunk1_and_chunk2',
       'euclidean_distance_chunk1_and_chunk3',
       'euclidean_distance_chunk2_and_chunk3']
].sum(axis=1)**2

In [76]:
df_filtered.sort_values(by='sum_distance', ascending=False).head(50) # sort_values(by='sum_logfreq', ascending=False).head(1000)

,count_of_chunks,corpus,chunk1,chunk2,chunk3,euclidean_distance_chunk1_and_chunk2,euclidean_distance_chunk1_and_chunk3,euclidean_distance_chunk2_and_chunk3,euclidean_corpus_and_chunk1,euclidean_corpus_and_chunk2,...,length_corpus,length_chunk1,length_chunk2,length_chunk3,logfreq_corpus,logfreq_chunk1,logfreq_chunk2,logfreq_chunk3,sum_logfreq,sum_distance
11324,3,hahaha,ha,ha,ha,0.000000,0.000000,0.000000,15.172641,15.172641,...,6,2,2,2,2.376577,6.178496,6.178496,6.178496,18.535487,45.517922
1005,3,nagymama,nagy,ma,ma,8.555860,8.555860,0.000000,22.019670,22.057728,...,8,4,2,2,4.000000,5.362324,5.356037,5.356037,16.074399,-226.675806
7270,3,temette,te,met,te,8.453837,0.000000,8.453837,15.369980,14.525012,...,7,2,3,2,2.611723,5.976475,4.000000,5.976475,15.952949,-240.604495
10212,3,tetemet,te,te,met,0.000000,8.453837,8.453837,15.027343,15.027343,...,7,2,2,3,2.432969,5.976475,5.976475,4.000000,15.952949,-241.470249
10982,3,nagypapám,nagy,pap,ám,7.198178,6.436804,5.650540,25.839767,26.452534,...,9,4,3,2,2.390935,5.362324,4.000000,4.292965,13.655289,-292.883597
2010,3,hajója,ha,jó,ja,8.152987,7.550838,6.158612,23.560698,23.459274,...,6,2,2,2,3.252610,6.178496,5.916272,5.058156,17.152924,-408.439347
10241,3,jamaikai,ja,mai,kai,8.202376,6.356954,7.506411,14.944223,15.693529,...,8,2,3,3,4.000000,5.058156,4.424228,3.269046,12.751430,-440.245800
5134,3,hajóhoz,ha,jó,hoz,8.152987,8.267520,7.735636,24.235058,24.426960,...,7,2,2,3,2.795185,6.178496,5.916272,4.024773,16.119541,-512.267690
11875,3,toronto,to,ron,to,11.888472,0.000000,11.888472,17.246298,17.231106,...,7,2,3,2,2.350248,4.057057,3.691258,4.057057,11.805373,-513.619327
3037,3,nagyanyám,nagy,any,ám,8.820455,6.436804,8.964212,21.343174,21.761572,...,9,4,3,2,3.057286,5.362324,4.000000,4.292965,13.655289,-520.690182
930,3,tetején,te,tej,én,6.454699,9.526695,8.458471,16.590647,16.141863,...,7,2,3,2,4.000000,5.976475,4.000000,6.157086,16.133561,-549.220012
2522,3,hallottalak,hall,ott,alak,8.792850,7.177156,8.969092,21.111242,20.366951,...,11,4,3,4,3.139564,4.000000,5.565866,4.000000,13.565866,-559.306927
5345,3,nagyanyja,nagy,any,ja,8.820455,7.011244,9.292104,22.317606,22.702461,...,9,4,3,2,2.774517,5.362324,4.000000,5.058156,14.420481,-563.254508
10291,3,tagadhatja,tag,adhat,ja,8.691010,8.223150,8.165420,20.404104,22.602943,...,10,3,5,2,2.428135,4.000000,3.195069,5.058156,12.253225,-565.136456
10418,3,alakokkal,alak,ok,kal,9.558112,5.341516,9.914415,13.332570,15.812009,...,9,4,2,3,2.419956,4.000000,4.570555,3.228657,11.799212,-573.110510
5598,3,hajaddal,haj,ad,dal,8.414463,8.991095,7.946470,20.330725,20.603029,...,8,3,2,3,2.748963,4.000000,4.265996,4.000000,12.265996,-581.084478
2446,3,tagadja,tag,ad,ja,9.013069,8.223150,8.253322,20.149792,20.756184,...,7,3,2,2,4.000000,4.000000,4.265996,5.058156,13.324153,-588.340276
7749,3,holttestemen,holt,teste,men,5.924662,10.236435,9.890821,26.226818,27.049515,...,12,4,5,3,2.579784,4.000000,3.732072,4.000000,11.732072,-597.872712
9210,3,élénken,él,én,ken,7.837418,10.611679,8.063389,21.596207,20.423880,...,7,2,2,3,4.000000,4.520929,6.157086,4.000000,14.678015,-641.048004
4157,3,kapjanak,kap,ja,nak,7.339210,9.582210,9.684326,21.085161,20.629595,...,8,3,2,3,2.897077,4.301377,5.058156,3.550106,12.909640,-646.116363
7630,3,anyahajó,anya,ha,jó,9.473166,9.360179,8.152987,26.487864,27.266060,...,8,4,2,2,4.000000,5.014869,6.178496,5.916272,17.109637,-647.036964
3828,3,közismert,köz,is,mert,8.860550,8.833230,9.077915,21.581547,22.489723,...,9,3,2,4,4.000000,4.000000,6.274002,5.682616,15.956618,-650.417708
7817,3,kaphatott,kap,hat,ott,9.301393,8.036938,9.398898,21.093828,20.300835,...,9,3,3,3,2.575188,4.301377,4.542788,5.565866,14.410031,-652.476453
7629,3,anyahajó,any,aha,jó,10.035417,9.426796,7.632212,25.836834,26.764500,...,8,3,3,2,4.000000,4.000000,4.701956,5.916272,14.618229,-654.035242
9018,3,végénél,vég,én,él,9.279320,9.743228,7.837418,19.673899,21.490995,...,7,3,2,2,2.499687,4.000000,6.157086,4.520929,14.678015,-657.448340
175,3,hallottad,hall,ott,ad,8.792850,8.363873,9.695351,20.882832,20.099663,...,9,4,3,2,4.250835,4.000000,5.565866,4.265996,13.831862,-659.677356
3707,3,ismertél,is,mert,él,9.077915,9.562719,8.358574,22.662149,21.953566,...,8,2,4,2,2.951823,6.274002,5.682616,4.520929,16.477547,-661.291489
2620,3,haverja,ha,ver,ja,10.028307,7.550838,9.462273,21.271479,20.682367,...,7,2,3,2,3.120574,6.178496,4.000000,5.058156,15.236652,-668.479550
6662,3,kaphatja,kap,hat,ja,9.301393,7.339210,10.428386,21.790977,20.930830,...,8,3,3,2,2.655138,4.301377,4.542788,5.058156,13.902322,-668.807422
1579,3,temetés,te,met,és,8.453837,9.194379,9.258888,15.254418,14.586521,...,7,2,3,2,4.000000,5.976475,4.000000,6.556242,16.532717,-678.389883
6148,3,haladjon,hal,ad,jon,9.544624,8.679688,9.292465,21.293518,21.139061,...,8,3,2,3,2.699838,4.108159,4.265996,3.248219,11.622374,-694.158448
7497,3,alkalmad,al,kal,mad,8.629684,9.940838,8.932953,22.035902,20.049845,...,8,2,3,3,2.595496,4.074268,3.228657,4.000000,11.302925,-694.209883
11355,3,nagymenők,nagy,men,ők,9.795351,7.709051,10.072720,21.071394,22.660910,...,9,4,3,2,2.374748,5.362324,4.000000,4.923886,14.286210,-694.598849
9338,3,anyagokkal,anyag,ok,kal,9.784763,7.514373,9.914415,13.045567,16.071190,...,10,5,2,3,2.482874,4.000000,4.570555,3.228657,11.799212,-696.673019
9956,3,lapokkal,lap,ok,kal,10.348918,6.990936,9.914415,14.170620,15.515347,...,8,3,2,3,2.447158,4.000000,4.570555,3.228657,11.799212,-699.614157
6351,3,fogadtad,fog,ad,tad,11.088690,10.450277,6.109174,19.564997,22.033909,...,8,3,2,3,2.683047,5.393961,4.265996,4.000000,13.659957,-700.584803
5231,3,anyámhoz,any,ám,hoz,8.964212,10.697639,8.064329,20.986984,23.087738,...,8,3,2,3,2.784617,4.000000,4.292965,4.024773,12.317737,-702.132476
8651,3,járjanak,jár,ja,nak,7.760757,10.328823,9.684326,21.106421,20.982235,...,8,3,2,3,2.523746,4.564749,5.058156,3.550106,13.173011,-709.017330
7383,3,tartottalak,tart,ott,alak,9.103975,9.899772,8.969092,20.705444,22.111128,...,11,4,3,4,2.603144,4.571429,5.565866,4.000000,14.137295,-717.054452
2607,3,hajókat,ha,jó,kat,8.152987,10.441750,9.570324,24.494612,24.573570,...,7,2,2,3,3.123852,6.178496,5.916272,3.212454,15.307222,-721.111506
10491,3,hajadban,haj,ad,ban,8.414463,9.263520,10.363987,20.052387,20.827496,...,8,3,2,3,2.414973,4.000000,4.265996,4.000000,12.265996,-725.819039
3223,3,központja,köz,pont,ja,8.948357,9.080007,10.188995,21.512121,23.650515,...,9,3,4,2,3.028978,4.000000,4.860847,5.058156,13.919003,-729.135446
3763,3,ezredest,ez,red,est,10.141928,9.579798,8.495434,20.904398,22.456152,...,8,2,3,3,2.945469,6.333684,4.000000,4.000000,14.333684,-730.179624
1534,3,adjanak,ad,ja,nak,8.253322,10.237529,9.684326,20.596266,21.170246,...,7,2,2,3,3.378943,4.265996,5.058156,3.550106,12.874259,-731.746110
6041,3,haverokkal,ha,ver,okkal,10.028307,8.861346,9.328797,21.756670,21.047501,...,10,2,3,5,2.710117,6.178496,4.000000,3.545678,13.724174,-732.162268
5546,3,alkalma,al,kal,ma,8.629684,10.052188,9.505305,15.611288,13.902240,...,7,2,3,2,2.753583,4.074268,3.228657,5.356037,12.658962,-749.466589
7928,3,akarhatja,akar,hat,ja,10.206157,7.943472,10.428386,21.690744,21.700184,...,9,4,3,2,2.567026,5.131564,4.542788,5.058156,14.732509,-751.323746
879,3,istenverte,isten,ver,te,9.066947,8.910011,10.266874,13.860101,15.513647,...,10,5,3,2,4.000000,4.935543,4.000000,5.976475,14.912017,-751.864034
7807,3,senorita,se,no,rita,9.232163,9.263329,10.131798,23.098230,22.583941,...,8,2,2,4,2.575188,5.185035,4.162982,3.470851,12.818868,-751.955300
1426,3,genetikai,gene,ti,kai,10.838678,7.245883,10.573395,21.574524,23.274576,...,9,4,2,3,4.000000,4.000000,4.868462,3.269046,12.137508,-753.701247

In [54]:
df_filtered[df_filtered.corpus == 'terápiát']

,count_of_chunks,corpus,chunk1,chunk2,chunk3,euclidean_distance_chunk1_and_chunk2,euclidean_distance_chunk1_and_chunk3,euclidean_distance_chunk2_and_chunk3,euclidean_corpus_and_chunk1,euclidean_corpus_and_chunk2,...,length_corpus,length_chunk1,length_chunk2,length_chunk3,logfreq_corpus,logfreq_chunk1,logfreq_chunk2,logfreq_chunk3,sum_logfreq,sum_distance
4990,3,terápiát,te,rá,piát,10.028425,15.879962,15.459969,26.342171,25.975481,...,8,2,2,4,2.810233,5.976475,5.386292,3.3638,14.726567,67.710526

In [72]:
multi_meaning = ['sejt', 'tér', 'járat', 'hajt', 'hossz', 'összehajt', 'krokett',
       'dominó', 'szóló', 'ellát', 'bolt', 'hal', 'fogoly', 'cankó',
       'bokszer', 'spicc', 'here', 'báb', 'sül', 'szarvas', 'hall', 'ár',
       'tuba', 'háló', 'seprű', 'él', 'boksz', 'szél', 'kirakat',
       'töltet', 'dob', 'bejárat', 'kijárat', 'csap', 'tűz', 'vár',
       'filé', 'sír', 'terem', 'fej', 'otthon', 'felhajtás', 'zár',
       'akna', 'szeg', 'ír', 'hegy', 'vonat', 'ring', 'csavar', 'varrat',
       'ing', 'szán', 'ujj', 'csík', 'csapás', 'viola', 'fal', 'vágat',
       'méret', 'fog', 'szív', 'ér', 'méh', 'áll', 'ég', 'tudat', 'zavar',
       'adat', 'nyom', 'levelezés', 'görög', 'szignál', 'trópus',
       'nyugta', 'tus', 'sertés', 'paradicsom', 'kivi', 'író', 'főzet',
       'köz', 'ezred', 'század', 'fél', 'diéta', 'rengeteg', 'dada',
       'fok', 'parti', 'biztos', 'tizedes', 'őr', 'hív', 'örökös',
       'homokos', 'kezes', 'mandarin', 'boltos', 'csempész', 'nő', 'fagy',
       'hajtás', 'vagyon', 'adó', 'tőke', 'öl', 'frank', 'líra', 'lábas',
       'dél', 'szög', 'vájat', 'titán', 'hét', 'lejárat', 'búcsú',
       'passzol', 'behajt', 'mer', 'költ', 'megér', 'kifejez', 'képes',
       'elszánt', 'matt', 'egy', 'sebes', 'derék', 'fő', 'ősz', 'volt',
       'hegyes', 'megjelent', 'roppant', 'ó', 'nem', 'elöl', 'korán',
       'elég', 'ki', 'rekedt', 'bárhol', 'haza']

In [74]:
df_filtered[
    df_filtered.corpus.isin(multi_meaning) | 
    df_filtered.chunk1.isin(multi_meaning) | 
    df_filtered.chunk2.isin(multi_meaning) | 
    df_filtered.chunk3.isin(multi_meaning)
].sort_values(by='sum_distance', ascending=False).head(10)

,count_of_chunks,corpus,chunk1,chunk2,chunk3,euclidean_distance_chunk1_and_chunk2,euclidean_distance_chunk1_and_chunk3,euclidean_distance_chunk2_and_chunk3,euclidean_corpus_and_chunk1,euclidean_corpus_and_chunk2,...,length_corpus,length_chunk1,length_chunk2,length_chunk3,logfreq_corpus,logfreq_chunk1,logfreq_chunk2,logfreq_chunk3,sum_logfreq,sum_distance
4299,3,végeznem,vég,ez,nem,10.777746,9.323895,10.384924,25.705338,27.515749,...,8,3,2,3,2.882525,4.000000,6.333684,6.820146,17.153831,50.306863
1167,3,tanácsadó,tan,ács,adó,10.392220,10.915308,9.847590,25.167583,26.652882,...,9,3,3,3,4.000000,4.000000,4.000000,4.000000,12.000000,47.627458
1920,3,szereznem,szer,ez,nem,10.612818,9.926379,10.384924,25.845654,25.929550,...,9,4,2,3,3.275081,3.134814,6.333684,6.820146,16.288645,46.854075
5477,3,egymásért,egy,más,ért,15.545871,13.028426,11.663611,27.166685,27.168612,...,9,3,3,3,2.761176,6.513669,5.199344,4.410440,16.123453,41.112691
5694,3,fogalmatok,fog,alma,tok,11.784644,13.390117,13.521954,23.938524,26.956772,...,10,3,4,3,2.737987,5.393961,4.000000,4.000000,13.393961,40.799940
489,3,egymáshoz,egy,más,hoz,15.545871,14.902903,9.792484,27.547989,27.261209,...,9,3,3,3,3.876680,6.513669,5.199344,4.024773,15.737786,40.740380
3707,3,ismertél,is,mert,él,9.077915,9.562719,8.358574,22.662149,21.953566,...,8,2,4,2,2.951823,6.274002,5.682616,4.520929,16.477547,40.666559
4467,3,egyszercsak,egy,szer,csak,14.391782,16.441442,12.769174,28.288284,26.531454,...,11,3,4,4,2.866287,6.513669,3.134814,6.202550,15.851034,39.744059
3828,3,közismert,köz,is,mert,8.860550,8.833230,9.077915,21.581547,22.489723,...,9,3,2,4,4.000000,4.000000,6.274002,5.682616,15.956618,39.534257
10116,3,miegymás,mi,egy,más,15.412855,11.571648,15.545871,26.708681,28.073294,...,8,2,3,3,2.439333,6.162454,6.513669,5.199344,17.875467,39.358871

In [7]:
df['WORD'] = df['EKSZ'].str.replace('_.*', '', regex=True)

In [8]:
df['COUNT_OF_MEANING'] = df['EKSZ'].str.extract(r'^[^_]*_(\d+)', expand=False).fillna('0').astype(int)

In [9]:
multi_meaning_words = df[df.COUNT_OF_MEANING > 1]['WORD'].unique()

In [15]:
multi2 = df['WORD'].value_counts()
multi2 = multi2[multi2 > 1]

In [18]:
len(set(multi_meaning_words) - set(multi2))

144

In [20]:
multi_meaning_words

array(['sejt', 'tér', 'járat', 'hajt', 'hossz', 'összehajt', 'krokett',
       'dominó', 'szóló', 'ellát', 'bolt', 'hal', 'fogoly', 'cankó',
       'bokszer', 'spicc', 'here', 'báb', 'sül', 'szarvas', 'hall', 'ár',
       'tuba', 'háló', 'seprű', 'él', 'boksz', 'szél', 'kirakat',
       'töltet', 'dob', 'bejárat', 'kijárat', 'csap', 'tűz', 'vár',
       'filé', 'sír', 'terem', 'fej', 'otthon', 'felhajtás', 'zár',
       'akna', 'szeg', 'ír', 'hegy', 'vonat', 'ring', 'csavar', 'varrat',
       'ing', 'szán', 'ujj', 'csík', 'csapás', 'viola', 'fal', 'vágat',
       'méret', 'fog', 'szív', 'ér', 'méh', 'áll', 'ég', 'tudat', 'zavar',
       'adat', 'nyom', 'levelezés', 'görög', 'szignál', 'trópus',
       'nyugta', 'tus', 'sertés', 'paradicsom', 'kivi', 'író', 'főzet',
       'köz', 'ezred', 'század', 'fél', 'diéta', 'rengeteg', 'dada',
       'fok', 'parti', 'biztos', 'tizedes', 'őr', 'hív', 'örökös',
       'homokos', 'kezes', 'mandarin', 'boltos', 'csempész', 'nő', 'fagy',
       'hajtás', 'vagyon', 'adó', 'tőke', 'öl', 'frank', 'líra', 'lábas',
       'dél', 'szög', 'vájat', 'titán', 'hét', 'lejárat', 'búcsú',
       'passzol', 'behajt', 'mer', 'költ', 'megér', 'kifejez', 'képes',
       'elszánt', 'matt', 'egy', 'sebes', 'derék', 'fő', 'ősz', 'volt',
       'hegyes', 'megjelent', 'roppant', 'ó', 'nem', 'elöl', 'korán',
       'elég', 'ki', 'rekedt', 'bárhol', 'haza'], dtype=object)